# Size for all blocks in Bytes
block_size=10240
# Policy for caching the blocks
policy=2
topology_directed=off
#output=out.out
#debug=debug.dbg
#UNIMPLEMENTED: topology_file=
#UNIMPLEMENTED: rounds_file=
barriers=off
#UNIMPLEMENTED: seed=0
#UNIMPLEMENTED: blocks_per_node=1
